#!/usr/bin/env bash
set -euo pipefail

# PreCompact Hook - Write Ralph Context Anchor
# Runs before auto-compaction to persist minimal loop state
# SECURITY: All inputs validated, variables quoted, timeouts enforced

# Exit codes:
# 0 - Success
# 2 - Blocking error (shown to user)

# Validate required environment
if [[ -z "${CLAUDEPROJECTDIR:-}" ]]; then
  echo "Error: CLAUDEPROJECTDIR not set" >&2
  exit 2
fi

# Set strict timeout for this script
readonly SCRIPT_TIMEOUT=60

# Build safe state file paths (validate no path traversal)
STATE_FILE="${CLAUDEPROJECTDIR}/.claude.ralph-orchestrator.local.md"
CONTEXT_FILE="${CLAUDEPROJECTDIR}/.ralph/context.md"
GOALS_XML="${CLAUDEPROJECTDIR}/.ralph/goals.xml"

# Validate paths don't contain traversal
for path in "$STATE_FILE" "$CONTEXT_FILE" "$GOALS_XML"; do
  if [[ "$path" == *".."* ]]; then
    echo "Error: Path traversal detected" >&2
    exit 2
  fi
done

# Read and validate hook input JSON from stdin
HOOK_INPUT="$(cat || true)"
if [[ -z "$HOOK_INPUT" ]]; then
  exit 0
fi

# Sanitize and validate JSON input
TRIGGER="$(echo "$HOOK_INPUT" | jq -er '.trigger // empty' 2>/dev/null || echo "")"
if [[ -z "$TRIGGER" ]]; then
  exit 0
fi

# Only proceed on auto compaction
if [[ "$TRIGGER" != "auto" ]]; then
  exit 0
fi

# If no orchestrator state, nothing to anchor
if [[ ! -f "$STATE_FILE" ]]; then
  exit 0
fi

# Extract YAML frontmatter from state file safely
FRONTMATTER="$(sed -n '1,/^---$/p' "$STATE_FILE" 2>/dev/null | sed '1d;$d' || true)"
if [[ -z "$FRONTMATTER" ]]; then
  echo "Error: Invalid state file format" >&2
  exit 2
fi

get_field() {
  local key="$1"
  echo "$FRONTMATTER" | awk -F': ' -v k="$key" '$1==k {print substr($0, length(k)+3)}' | head -n1
}

ITERATION="$(get_field iteration)"
MAX_ITERATIONS="$(get_field max_iterations)"
COMPLETION_PROMISE_RAW="$(get_field completion_promise)"
GOALS_FILE="$(get_field goals_file)"

# Validate iteration is numeric
if [[ -n "$ITERATION" && ! "$ITERATION" =~ ^[0-9]+$ ]]; then
  echo "Error: Invalid iteration value" >&2
  exit 2
fi

# Decode completion promise safely
COMPLETION_PROMISE=""
if [[ "$COMPLETION_PROMISE_RAW" != "null" && -n "$COMPLETION_PROMISE_RAW" ]]; then
  COMPLETION_PROMISE="$(timeout 10 python3 - <<PY
import json, sys
try:
    print(json.loads(sys.argv[1]))
except:
    sys.exit(1)
PY
"$COMPLETION_PROMISE_RAW" 2>/dev/null || echo "")"
fi

# Read constant prompt from state file body (after second ---)
CONSTANT_PROMPT="$(awk 'BEGIN{s=0} /^---$/{s++; if(s==2){getline; print; exit}}' "$STATE_FILE" 2>/dev/null || true)"

# Find current active goal with timeout
CURRENT_GOAL_ID=""
if [[ -f "$GOALS_XML" ]]; then
  CURRENT_GOAL_ID="$(timeout 30 python3 - <<'PYTHON_SCRIPT'
import sys
import xml.etree.ElementTree as ET

try:
    tree = ET.parse(sys.argv[1])
    root = tree.getroot()

    for goal in root.findall('goal'):
        if goal.get('status') != 'done':
            print(goal.get('id', 'unknown'))
            sys.exit(0)

    print("NONE")
    sys.exit(0)
except Exception as e:
    print("ERROR")
    sys.exit(1)
PYTHON_SCRIPT
"$GOALS_XML" 2>/dev/null || echo "ERROR")"
fi

# Get verifier command from current goal with timeout
VERIFIER_CMD=""
if [[ -n "$CURRENT_GOAL_ID" && "$CURRENT_GOAL_ID" != "NONE" && "$CURRENT_GOAL_ID" != "ERROR" ]]; then
  # Sanitize goal ID (alphanumeric, underscore, hyphen only)
  if [[ ! "$CURRENT_GOAL_ID" =~ ^[A-Za-z0-9_-]+$ ]]; then
    echo "Error: Invalid goal ID format" >&2
    exit 2
  fi

  VERIFIER_CMD="$(timeout 30 python3 - <<'PYTHON_SCRIPT'
import sys
import xml.etree.ElementTree as ET

try:
    tree = ET.parse(sys.argv[1])
    root = tree.getroot()

    goal_id = sys.argv[2]
    for goal in root.findall('goal'):
        if goal.get('id') == goal_id:
            verify_elem = goal.find('verify')
            if verify_elem is not None:
                first_cmd = verify_elem.find('cmd')
                if first_cmd is not None and first_cmd.text:
                    print(first_cmd.text.strip())
                    sys.exit(0)
            break
    print("")
    sys.exit(0)
except Exception as e:
    print("")
    sys.exit(1)
PYTHON_SCRIPT
"$GOALS_XML" "$CURRENT_GOAL_ID" 2>/dev/null || echo "")"
fi

# Write minimal context anchor safely
cat > "$CONTEXT_FILE" <<EOF
# Ralph Orchestrator Context (Auto-Compact Anchor)

## Loop State
- Active: true
- Iteration: ${ITERATION}
- Max Iterations: ${MAX_ITERATIONS}

## Files
- State File: ${STATE_FILE}
- Goals XML: ${GOALS_XML}
- Constant Prompt: in state file body

## Current Goal
- ID: ${CURRENT_GOAL_ID}

## Completion
- Promise: ${COMPLETION_PROMISE}
- Pattern: promiseGOAL {ID} DONEpromise

## Verifier
- Command: ${VERIFIER_CMD}

---
Auto-generated by PreCompact hook. Read this first after compaction.
EOF

# Success - no output to keep PreCompact silent
exit 0
